package com.etcj.delivery.dao;

import com.etcj.delivery.api.model.Packet;
import com.etcj.delivery.api.model.PacketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    long countByExample(PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    int deleteByExample(PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    int insert(Packet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    int insertSelective(Packet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    List<Packet> selectByExample(PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    Packet selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") Packet record, @Param("example") PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    int updateByExample(@Param("record") Packet record, @Param("example") PacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    int updateByPrimaryKeySelective(Packet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    int updateByPrimaryKey(Packet record);

    int insertBatchSelective(List<Packet> records);
}