package com.etcj.delivery.dao;

import com.etcj.delivery.api.model.PlatMobileDevice;
import com.etcj.delivery.api.model.PlatMobileDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatMobileDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    long countByExample(PlatMobileDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int deleteByExample(PlatMobileDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int insert(PlatMobileDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int insertSelective(PlatMobileDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    List<PlatMobileDevice> selectByExample(PlatMobileDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    PlatMobileDevice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") PlatMobileDevice record, @Param("example") PlatMobileDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByExample(@Param("record") PlatMobileDevice record, @Param("example") PlatMobileDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByPrimaryKeySelective(PlatMobileDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_device
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByPrimaryKey(PlatMobileDevice record);

    int insertBatchSelective(List<PlatMobileDevice> records);
}