package com.etcj.delivery.dao;

import com.etcj.delivery.api.model.PlatMobileLog;
import com.etcj.delivery.api.model.PlatMobileLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatMobileLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    long countByExample(PlatMobileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int deleteByExample(PlatMobileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int insert(PlatMobileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int insertSelective(PlatMobileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    List<PlatMobileLog> selectByExampleWithBLOBs(PlatMobileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    List<PlatMobileLog> selectByExample(PlatMobileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    PlatMobileLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") PlatMobileLog record, @Param("example") PlatMobileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") PlatMobileLog record, @Param("example") PlatMobileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByExample(@Param("record") PlatMobileLog record, @Param("example") PlatMobileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByPrimaryKeySelective(PlatMobileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(PlatMobileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_mobile_log
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    int updateByPrimaryKey(PlatMobileLog record);

    int insertBatchSelective(List<PlatMobileLog> records);
}