package com.etcj.delivery.dao;

import com.etcj.delivery.api.model.StationStation;
import com.etcj.delivery.api.model.StationStationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StationStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    long countByExample(StationStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    int deleteByExample(StationStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    int insert(StationStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    int insertSelective(StationStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    List<StationStation> selectByExample(StationStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    StationStation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") StationStation record, @Param("example") StationStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    int updateByExample(@Param("record") StationStation record, @Param("example") StationStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    int updateByPrimaryKeySelective(StationStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    int updateByPrimaryKey(StationStation record);

    int insertBatchSelective(List<StationStation> records);
}