package com.etcj.delivery.dao;

import com.etcj.delivery.api.model.White;
import com.etcj.delivery.api.model.WhiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WhiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    long countByExample(WhiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    int deleteByExample(WhiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    int insert(White record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    int insertSelective(White record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    List<White> selectByExample(WhiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    White selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") White record, @Param("example") WhiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    int updateByExample(@Param("record") White record, @Param("example") WhiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    int updateByPrimaryKeySelective(White record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    int updateByPrimaryKey(White record);

    int insertBatchSelective(List<White> records);
}