package com.etcj.delivery.api.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PacketExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public PacketExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(String value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(String value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(String value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(String value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(String value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(String value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLike(String value) {
            addCriterion("shop_id like", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotLike(String value) {
            addCriterion("shop_id not like", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<String> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<String> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(String value1, String value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(String value1, String value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNull() {
            addCriterion("station_id is null");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("station_id is not null");
            return (Criteria) this;
        }

        public Criteria andStationIdEqualTo(String value) {
            addCriterion("station_id =", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotEqualTo(String value) {
            addCriterion("station_id <>", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThan(String value) {
            addCriterion("station_id >", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(String value) {
            addCriterion("station_id >=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThan(String value) {
            addCriterion("station_id <", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThanOrEqualTo(String value) {
            addCriterion("station_id <=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLike(String value) {
            addCriterion("station_id like", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotLike(String value) {
            addCriterion("station_id not like", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdIn(List<String> values) {
            addCriterion("station_id in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotIn(List<String> values) {
            addCriterion("station_id not in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdBetween(String value1, String value2) {
            addCriterion("station_id between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotBetween(String value1, String value2) {
            addCriterion("station_id not between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andFullIsNull() {
            addCriterion("is_full is null");
            return (Criteria) this;
        }

        public Criteria andFullIsNotNull() {
            addCriterion("is_full is not null");
            return (Criteria) this;
        }

        public Criteria andFullEqualTo(Boolean value) {
            addCriterion("is_full =", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullNotEqualTo(Boolean value) {
            addCriterion("is_full <>", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullGreaterThan(Boolean value) {
            addCriterion("is_full >", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_full >=", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullLessThan(Boolean value) {
            addCriterion("is_full <", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullLessThanOrEqualTo(Boolean value) {
            addCriterion("is_full <=", value, "full");
            return (Criteria) this;
        }

        public Criteria andFullIn(List<Boolean> values) {
            addCriterion("is_full in", values, "full");
            return (Criteria) this;
        }

        public Criteria andFullNotIn(List<Boolean> values) {
            addCriterion("is_full not in", values, "full");
            return (Criteria) this;
        }

        public Criteria andFullBetween(Boolean value1, Boolean value2) {
            addCriterion("is_full between", value1, value2, "full");
            return (Criteria) this;
        }

        public Criteria andFullNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_full not between", value1, value2, "full");
            return (Criteria) this;
        }

        public Criteria andTimeoutIsNull() {
            addCriterion("is_timeout is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutIsNotNull() {
            addCriterion("is_timeout is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutEqualTo(Boolean value) {
            addCriterion("is_timeout =", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotEqualTo(Boolean value) {
            addCriterion("is_timeout <>", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutGreaterThan(Boolean value) {
            addCriterion("is_timeout >", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_timeout >=", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutLessThan(Boolean value) {
            addCriterion("is_timeout <", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutLessThanOrEqualTo(Boolean value) {
            addCriterion("is_timeout <=", value, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutIn(List<Boolean> values) {
            addCriterion("is_timeout in", values, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotIn(List<Boolean> values) {
            addCriterion("is_timeout not in", values, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutBetween(Boolean value1, Boolean value2) {
            addCriterion("is_timeout between", value1, value2, "timeout");
            return (Criteria) this;
        }

        public Criteria andTimeoutNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_timeout not between", value1, value2, "timeout");
            return (Criteria) this;
        }

        public Criteria andPacketTypeIsNull() {
            addCriterion("packet_type is null");
            return (Criteria) this;
        }

        public Criteria andPacketTypeIsNotNull() {
            addCriterion("packet_type is not null");
            return (Criteria) this;
        }

        public Criteria andPacketTypeEqualTo(String value) {
            addCriterion("packet_type =", value, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeNotEqualTo(String value) {
            addCriterion("packet_type <>", value, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeGreaterThan(String value) {
            addCriterion("packet_type >", value, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeGreaterThanOrEqualTo(String value) {
            addCriterion("packet_type >=", value, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeLessThan(String value) {
            addCriterion("packet_type <", value, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeLessThanOrEqualTo(String value) {
            addCriterion("packet_type <=", value, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeLike(String value) {
            addCriterion("packet_type like", value, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeNotLike(String value) {
            addCriterion("packet_type not like", value, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeIn(List<String> values) {
            addCriterion("packet_type in", values, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeNotIn(List<String> values) {
            addCriterion("packet_type not in", values, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeBetween(String value1, String value2) {
            addCriterion("packet_type between", value1, value2, "packetType");
            return (Criteria) this;
        }

        public Criteria andPacketTypeNotBetween(String value1, String value2) {
            addCriterion("packet_type not between", value1, value2, "packetType");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderIsNull() {
            addCriterion("number_of_order is null");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderIsNotNull() {
            addCriterion("number_of_order is not null");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderEqualTo(Integer value) {
            addCriterion("number_of_order =", value, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderNotEqualTo(Integer value) {
            addCriterion("number_of_order <>", value, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderGreaterThan(Integer value) {
            addCriterion("number_of_order >", value, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_of_order >=", value, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderLessThan(Integer value) {
            addCriterion("number_of_order <", value, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderLessThanOrEqualTo(Integer value) {
            addCriterion("number_of_order <=", value, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderIn(List<Integer> values) {
            addCriterion("number_of_order in", values, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderNotIn(List<Integer> values) {
            addCriterion("number_of_order not in", values, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderBetween(Integer value1, Integer value2) {
            addCriterion("number_of_order between", value1, value2, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("number_of_order not between", value1, value2, "numberOfOrder");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealIsNull() {
            addCriterion("number_of_meal is null");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealIsNotNull() {
            addCriterion("number_of_meal is not null");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealEqualTo(Integer value) {
            addCriterion("number_of_meal =", value, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealNotEqualTo(Integer value) {
            addCriterion("number_of_meal <>", value, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealGreaterThan(Integer value) {
            addCriterion("number_of_meal >", value, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_of_meal >=", value, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealLessThan(Integer value) {
            addCriterion("number_of_meal <", value, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealLessThanOrEqualTo(Integer value) {
            addCriterion("number_of_meal <=", value, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealIn(List<Integer> values) {
            addCriterion("number_of_meal in", values, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealNotIn(List<Integer> values) {
            addCriterion("number_of_meal not in", values, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealBetween(Integer value1, Integer value2) {
            addCriterion("number_of_meal between", value1, value2, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andNumberOfMealNotBetween(Integer value1, Integer value2) {
            addCriterion("number_of_meal not between", value1, value2, "numberOfMeal");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeIsNull() {
            addCriterion("packet_volume is null");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeIsNotNull() {
            addCriterion("packet_volume is not null");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeEqualTo(Integer value) {
            addCriterion("packet_volume =", value, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeNotEqualTo(Integer value) {
            addCriterion("packet_volume <>", value, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeGreaterThan(Integer value) {
            addCriterion("packet_volume >", value, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeGreaterThanOrEqualTo(Integer value) {
            addCriterion("packet_volume >=", value, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeLessThan(Integer value) {
            addCriterion("packet_volume <", value, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeLessThanOrEqualTo(Integer value) {
            addCriterion("packet_volume <=", value, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeIn(List<Integer> values) {
            addCriterion("packet_volume in", values, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeNotIn(List<Integer> values) {
            addCriterion("packet_volume not in", values, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeBetween(Integer value1, Integer value2) {
            addCriterion("packet_volume between", value1, value2, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketVolumeNotBetween(Integer value1, Integer value2) {
            addCriterion("packet_volume not between", value1, value2, "packetVolume");
            return (Criteria) this;
        }

        public Criteria andPacketDurationIsNull() {
            addCriterion("packet_duration is null");
            return (Criteria) this;
        }

        public Criteria andPacketDurationIsNotNull() {
            addCriterion("packet_duration is not null");
            return (Criteria) this;
        }

        public Criteria andPacketDurationEqualTo(Integer value) {
            addCriterion("packet_duration =", value, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andPacketDurationNotEqualTo(Integer value) {
            addCriterion("packet_duration <>", value, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andPacketDurationGreaterThan(Integer value) {
            addCriterion("packet_duration >", value, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andPacketDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("packet_duration >=", value, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andPacketDurationLessThan(Integer value) {
            addCriterion("packet_duration <", value, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andPacketDurationLessThanOrEqualTo(Integer value) {
            addCriterion("packet_duration <=", value, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andPacketDurationIn(List<Integer> values) {
            addCriterion("packet_duration in", values, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andPacketDurationNotIn(List<Integer> values) {
            addCriterion("packet_duration not in", values, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andPacketDurationBetween(Integer value1, Integer value2) {
            addCriterion("packet_duration between", value1, value2, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andPacketDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("packet_duration not between", value1, value2, "packetDuration");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisIsNull() {
            addCriterion("timeout_limit_millis is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisIsNotNull() {
            addCriterion("timeout_limit_millis is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisEqualTo(Long value) {
            addCriterion("timeout_limit_millis =", value, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisNotEqualTo(Long value) {
            addCriterion("timeout_limit_millis <>", value, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisGreaterThan(Long value) {
            addCriterion("timeout_limit_millis >", value, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisGreaterThanOrEqualTo(Long value) {
            addCriterion("timeout_limit_millis >=", value, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisLessThan(Long value) {
            addCriterion("timeout_limit_millis <", value, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisLessThanOrEqualTo(Long value) {
            addCriterion("timeout_limit_millis <=", value, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisIn(List<Long> values) {
            addCriterion("timeout_limit_millis in", values, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisNotIn(List<Long> values) {
            addCriterion("timeout_limit_millis not in", values, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisBetween(Long value1, Long value2) {
            addCriterion("timeout_limit_millis between", value1, value2, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutLimitMillisNotBetween(Long value1, Long value2) {
            addCriterion("timeout_limit_millis not between", value1, value2, "timeoutLimitMillis");
            return (Criteria) this;
        }

        public Criteria andPacketStatusIsNull() {
            addCriterion("packet_status is null");
            return (Criteria) this;
        }

        public Criteria andPacketStatusIsNotNull() {
            addCriterion("packet_status is not null");
            return (Criteria) this;
        }

        public Criteria andPacketStatusEqualTo(String value) {
            addCriterion("packet_status =", value, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusNotEqualTo(String value) {
            addCriterion("packet_status <>", value, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusGreaterThan(String value) {
            addCriterion("packet_status >", value, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusGreaterThanOrEqualTo(String value) {
            addCriterion("packet_status >=", value, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusLessThan(String value) {
            addCriterion("packet_status <", value, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusLessThanOrEqualTo(String value) {
            addCriterion("packet_status <=", value, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusLike(String value) {
            addCriterion("packet_status like", value, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusNotLike(String value) {
            addCriterion("packet_status not like", value, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusIn(List<String> values) {
            addCriterion("packet_status in", values, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusNotIn(List<String> values) {
            addCriterion("packet_status not in", values, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusBetween(String value1, String value2) {
            addCriterion("packet_status between", value1, value2, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andPacketStatusNotBetween(String value1, String value2) {
            addCriterion("packet_status not between", value1, value2, "packetStatus");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeIsNull() {
            addCriterion("delivery_mode is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeIsNotNull() {
            addCriterion("delivery_mode is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeEqualTo(String value) {
            addCriterion("delivery_mode =", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeNotEqualTo(String value) {
            addCriterion("delivery_mode <>", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeGreaterThan(String value) {
            addCriterion("delivery_mode >", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeGreaterThanOrEqualTo(String value) {
            addCriterion("delivery_mode >=", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeLessThan(String value) {
            addCriterion("delivery_mode <", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeLessThanOrEqualTo(String value) {
            addCriterion("delivery_mode <=", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeLike(String value) {
            addCriterion("delivery_mode like", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeNotLike(String value) {
            addCriterion("delivery_mode not like", value, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeIn(List<String> values) {
            addCriterion("delivery_mode in", values, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeNotIn(List<String> values) {
            addCriterion("delivery_mode not in", values, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeBetween(String value1, String value2) {
            addCriterion("delivery_mode between", value1, value2, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andDeliveryModeNotBetween(String value1, String value2) {
            addCriterion("delivery_mode not between", value1, value2, "deliveryMode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisIsNull() {
            addCriterion("create_time_millis is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisIsNotNull() {
            addCriterion("create_time_millis is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisEqualTo(Long value) {
            addCriterion("create_time_millis =", value, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisNotEqualTo(Long value) {
            addCriterion("create_time_millis <>", value, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisGreaterThan(Long value) {
            addCriterion("create_time_millis >", value, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time_millis >=", value, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisLessThan(Long value) {
            addCriterion("create_time_millis <", value, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisLessThanOrEqualTo(Long value) {
            addCriterion("create_time_millis <=", value, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisIn(List<Long> values) {
            addCriterion("create_time_millis in", values, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisNotIn(List<Long> values) {
            addCriterion("create_time_millis not in", values, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisBetween(Long value1, Long value2) {
            addCriterion("create_time_millis between", value1, value2, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCreateTimeMillisNotBetween(Long value1, Long value2) {
            addCriterion("create_time_millis not between", value1, value2, "createTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisIsNull() {
            addCriterion("finish_time_millis is null");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisIsNotNull() {
            addCriterion("finish_time_millis is not null");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisEqualTo(Long value) {
            addCriterion("finish_time_millis =", value, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisNotEqualTo(Long value) {
            addCriterion("finish_time_millis <>", value, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisGreaterThan(Long value) {
            addCriterion("finish_time_millis >", value, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisGreaterThanOrEqualTo(Long value) {
            addCriterion("finish_time_millis >=", value, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisLessThan(Long value) {
            addCriterion("finish_time_millis <", value, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisLessThanOrEqualTo(Long value) {
            addCriterion("finish_time_millis <=", value, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisIn(List<Long> values) {
            addCriterion("finish_time_millis in", values, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisNotIn(List<Long> values) {
            addCriterion("finish_time_millis not in", values, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisBetween(Long value1, Long value2) {
            addCriterion("finish_time_millis between", value1, value2, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFinishTimeMillisNotBetween(Long value1, Long value2) {
            addCriterion("finish_time_millis not between", value1, value2, "finishTimeMillis");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeIsNull() {
            addCriterion("consuming_time is null");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeIsNotNull() {
            addCriterion("consuming_time is not null");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeEqualTo(Long value) {
            addCriterion("consuming_time =", value, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeNotEqualTo(Long value) {
            addCriterion("consuming_time <>", value, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeGreaterThan(Long value) {
            addCriterion("consuming_time >", value, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("consuming_time >=", value, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeLessThan(Long value) {
            addCriterion("consuming_time <", value, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeLessThanOrEqualTo(Long value) {
            addCriterion("consuming_time <=", value, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeIn(List<Long> values) {
            addCriterion("consuming_time in", values, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeNotIn(List<Long> values) {
            addCriterion("consuming_time not in", values, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeBetween(Long value1, Long value2) {
            addCriterion("consuming_time between", value1, value2, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andConsumingTimeNotBetween(Long value1, Long value2) {
            addCriterion("consuming_time not between", value1, value2, "consumingTime");
            return (Criteria) this;
        }

        public Criteria andRiderIdIsNull() {
            addCriterion("rider_id is null");
            return (Criteria) this;
        }

        public Criteria andRiderIdIsNotNull() {
            addCriterion("rider_id is not null");
            return (Criteria) this;
        }

        public Criteria andRiderIdEqualTo(String value) {
            addCriterion("rider_id =", value, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdNotEqualTo(String value) {
            addCriterion("rider_id <>", value, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdGreaterThan(String value) {
            addCriterion("rider_id >", value, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdGreaterThanOrEqualTo(String value) {
            addCriterion("rider_id >=", value, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdLessThan(String value) {
            addCriterion("rider_id <", value, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdLessThanOrEqualTo(String value) {
            addCriterion("rider_id <=", value, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdLike(String value) {
            addCriterion("rider_id like", value, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdNotLike(String value) {
            addCriterion("rider_id not like", value, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdIn(List<String> values) {
            addCriterion("rider_id in", values, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdNotIn(List<String> values) {
            addCriterion("rider_id not in", values, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdBetween(String value1, String value2) {
            addCriterion("rider_id between", value1, value2, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderIdNotBetween(String value1, String value2) {
            addCriterion("rider_id not between", value1, value2, "riderId");
            return (Criteria) this;
        }

        public Criteria andRiderNameIsNull() {
            addCriterion("rider_name is null");
            return (Criteria) this;
        }

        public Criteria andRiderNameIsNotNull() {
            addCriterion("rider_name is not null");
            return (Criteria) this;
        }

        public Criteria andRiderNameEqualTo(String value) {
            addCriterion("rider_name =", value, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameNotEqualTo(String value) {
            addCriterion("rider_name <>", value, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameGreaterThan(String value) {
            addCriterion("rider_name >", value, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameGreaterThanOrEqualTo(String value) {
            addCriterion("rider_name >=", value, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameLessThan(String value) {
            addCriterion("rider_name <", value, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameLessThanOrEqualTo(String value) {
            addCriterion("rider_name <=", value, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameLike(String value) {
            addCriterion("rider_name like", value, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameNotLike(String value) {
            addCriterion("rider_name not like", value, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameIn(List<String> values) {
            addCriterion("rider_name in", values, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameNotIn(List<String> values) {
            addCriterion("rider_name not in", values, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameBetween(String value1, String value2) {
            addCriterion("rider_name between", value1, value2, "riderName");
            return (Criteria) this;
        }

        public Criteria andRiderNameNotBetween(String value1, String value2) {
            addCriterion("rider_name not between", value1, value2, "riderName");
            return (Criteria) this;
        }

        public Criteria andAllotTimeIsNull() {
            addCriterion("allot_time is null");
            return (Criteria) this;
        }

        public Criteria andAllotTimeIsNotNull() {
            addCriterion("allot_time is not null");
            return (Criteria) this;
        }

        public Criteria andAllotTimeEqualTo(Date value) {
            addCriterion("allot_time =", value, "allotTime");
            return (Criteria) this;
        }

        public Criteria andAllotTimeNotEqualTo(Date value) {
            addCriterion("allot_time <>", value, "allotTime");
            return (Criteria) this;
        }

        public Criteria andAllotTimeGreaterThan(Date value) {
            addCriterion("allot_time >", value, "allotTime");
            return (Criteria) this;
        }

        public Criteria andAllotTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("allot_time >=", value, "allotTime");
            return (Criteria) this;
        }

        public Criteria andAllotTimeLessThan(Date value) {
            addCriterion("allot_time <", value, "allotTime");
            return (Criteria) this;
        }

        public Criteria andAllotTimeLessThanOrEqualTo(Date value) {
            addCriterion("allot_time <=", value, "allotTime");
            return (Criteria) this;
        }

        public Criteria andAllotTimeIn(List<Date> values) {
            addCriterion("allot_time in", values, "allotTime");
            return (Criteria) this;
        }

        public Criteria andAllotTimeNotIn(List<Date> values) {
            addCriterion("allot_time not in", values, "allotTime");
            return (Criteria) this;
        }

        public Criteria andAllotTimeBetween(Date value1, Date value2) {
            addCriterion("allot_time between", value1, value2, "allotTime");
            return (Criteria) this;
        }

        public Criteria andAllotTimeNotBetween(Date value1, Date value2) {
            addCriterion("allot_time not between", value1, value2, "allotTime");
            return (Criteria) this;
        }

        public Criteria andScheduleCountIsNull() {
            addCriterion("schedule_count is null");
            return (Criteria) this;
        }

        public Criteria andScheduleCountIsNotNull() {
            addCriterion("schedule_count is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleCountEqualTo(Integer value) {
            addCriterion("schedule_count =", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountNotEqualTo(Integer value) {
            addCriterion("schedule_count <>", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountGreaterThan(Integer value) {
            addCriterion("schedule_count >", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("schedule_count >=", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountLessThan(Integer value) {
            addCriterion("schedule_count <", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountLessThanOrEqualTo(Integer value) {
            addCriterion("schedule_count <=", value, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountIn(List<Integer> values) {
            addCriterion("schedule_count in", values, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountNotIn(List<Integer> values) {
            addCriterion("schedule_count not in", values, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountBetween(Integer value1, Integer value2) {
            addCriterion("schedule_count between", value1, value2, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andScheduleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("schedule_count not between", value1, value2, "scheduleCount");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andAllottingIsNull() {
            addCriterion("is_allotting is null");
            return (Criteria) this;
        }

        public Criteria andAllottingIsNotNull() {
            addCriterion("is_allotting is not null");
            return (Criteria) this;
        }

        public Criteria andAllottingEqualTo(Boolean value) {
            addCriterion("is_allotting =", value, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottingNotEqualTo(Boolean value) {
            addCriterion("is_allotting <>", value, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottingGreaterThan(Boolean value) {
            addCriterion("is_allotting >", value, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottingGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_allotting >=", value, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottingLessThan(Boolean value) {
            addCriterion("is_allotting <", value, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottingLessThanOrEqualTo(Boolean value) {
            addCriterion("is_allotting <=", value, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottingIn(List<Boolean> values) {
            addCriterion("is_allotting in", values, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottingNotIn(List<Boolean> values) {
            addCriterion("is_allotting not in", values, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottingBetween(Boolean value1, Boolean value2) {
            addCriterion("is_allotting between", value1, value2, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottingNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_allotting not between", value1, value2, "allotting");
            return (Criteria) this;
        }

        public Criteria andAllottedIsNull() {
            addCriterion("is_allotted is null");
            return (Criteria) this;
        }

        public Criteria andAllottedIsNotNull() {
            addCriterion("is_allotted is not null");
            return (Criteria) this;
        }

        public Criteria andAllottedEqualTo(Boolean value) {
            addCriterion("is_allotted =", value, "allotted");
            return (Criteria) this;
        }

        public Criteria andAllottedNotEqualTo(Boolean value) {
            addCriterion("is_allotted <>", value, "allotted");
            return (Criteria) this;
        }

        public Criteria andAllottedGreaterThan(Boolean value) {
            addCriterion("is_allotted >", value, "allotted");
            return (Criteria) this;
        }

        public Criteria andAllottedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_allotted >=", value, "allotted");
            return (Criteria) this;
        }

        public Criteria andAllottedLessThan(Boolean value) {
            addCriterion("is_allotted <", value, "allotted");
            return (Criteria) this;
        }

        public Criteria andAllottedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_allotted <=", value, "allotted");
            return (Criteria) this;
        }

        public Criteria andAllottedIn(List<Boolean> values) {
            addCriterion("is_allotted in", values, "allotted");
            return (Criteria) this;
        }

        public Criteria andAllottedNotIn(List<Boolean> values) {
            addCriterion("is_allotted not in", values, "allotted");
            return (Criteria) this;
        }

        public Criteria andAllottedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_allotted between", value1, value2, "allotted");
            return (Criteria) this;
        }

        public Criteria andAllottedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_allotted not between", value1, value2, "allotted");
            return (Criteria) this;
        }

        public Criteria andEmptyIsNull() {
            addCriterion("is_empty is null");
            return (Criteria) this;
        }

        public Criteria andEmptyIsNotNull() {
            addCriterion("is_empty is not null");
            return (Criteria) this;
        }

        public Criteria andEmptyEqualTo(Boolean value) {
            addCriterion("is_empty =", value, "empty");
            return (Criteria) this;
        }

        public Criteria andEmptyNotEqualTo(Boolean value) {
            addCriterion("is_empty <>", value, "empty");
            return (Criteria) this;
        }

        public Criteria andEmptyGreaterThan(Boolean value) {
            addCriterion("is_empty >", value, "empty");
            return (Criteria) this;
        }

        public Criteria andEmptyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_empty >=", value, "empty");
            return (Criteria) this;
        }

        public Criteria andEmptyLessThan(Boolean value) {
            addCriterion("is_empty <", value, "empty");
            return (Criteria) this;
        }

        public Criteria andEmptyLessThanOrEqualTo(Boolean value) {
            addCriterion("is_empty <=", value, "empty");
            return (Criteria) this;
        }

        public Criteria andEmptyIn(List<Boolean> values) {
            addCriterion("is_empty in", values, "empty");
            return (Criteria) this;
        }

        public Criteria andEmptyNotIn(List<Boolean> values) {
            addCriterion("is_empty not in", values, "empty");
            return (Criteria) this;
        }

        public Criteria andEmptyBetween(Boolean value1, Boolean value2) {
            addCriterion("is_empty between", value1, value2, "empty");
            return (Criteria) this;
        }

        public Criteria andEmptyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_empty not between", value1, value2, "empty");
            return (Criteria) this;
        }

        public Criteria andCollectingIsNull() {
            addCriterion("is_collecting is null");
            return (Criteria) this;
        }

        public Criteria andCollectingIsNotNull() {
            addCriterion("is_collecting is not null");
            return (Criteria) this;
        }

        public Criteria andCollectingEqualTo(Boolean value) {
            addCriterion("is_collecting =", value, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingNotEqualTo(Boolean value) {
            addCriterion("is_collecting <>", value, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingGreaterThan(Boolean value) {
            addCriterion("is_collecting >", value, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_collecting >=", value, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingLessThan(Boolean value) {
            addCriterion("is_collecting <", value, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingLessThanOrEqualTo(Boolean value) {
            addCriterion("is_collecting <=", value, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingIn(List<Boolean> values) {
            addCriterion("is_collecting in", values, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingNotIn(List<Boolean> values) {
            addCriterion("is_collecting not in", values, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingBetween(Boolean value1, Boolean value2) {
            addCriterion("is_collecting between", value1, value2, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_collecting not between", value1, value2, "collecting");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisIsNull() {
            addCriterion("collecting_time_millis is null");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisIsNotNull() {
            addCriterion("collecting_time_millis is not null");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisEqualTo(Long value) {
            addCriterion("collecting_time_millis =", value, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisNotEqualTo(Long value) {
            addCriterion("collecting_time_millis <>", value, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisGreaterThan(Long value) {
            addCriterion("collecting_time_millis >", value, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisGreaterThanOrEqualTo(Long value) {
            addCriterion("collecting_time_millis >=", value, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisLessThan(Long value) {
            addCriterion("collecting_time_millis <", value, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisLessThanOrEqualTo(Long value) {
            addCriterion("collecting_time_millis <=", value, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisIn(List<Long> values) {
            addCriterion("collecting_time_millis in", values, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisNotIn(List<Long> values) {
            addCriterion("collecting_time_millis not in", values, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisBetween(Long value1, Long value2) {
            addCriterion("collecting_time_millis between", value1, value2, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andCollectingTimeMillisNotBetween(Long value1, Long value2) {
            addCriterion("collecting_time_millis not between", value1, value2, "collectingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisIsNull() {
            addCriterion("full_time_millis is null");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisIsNotNull() {
            addCriterion("full_time_millis is not null");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisEqualTo(Long value) {
            addCriterion("full_time_millis =", value, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisNotEqualTo(Long value) {
            addCriterion("full_time_millis <>", value, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisGreaterThan(Long value) {
            addCriterion("full_time_millis >", value, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisGreaterThanOrEqualTo(Long value) {
            addCriterion("full_time_millis >=", value, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisLessThan(Long value) {
            addCriterion("full_time_millis <", value, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisLessThanOrEqualTo(Long value) {
            addCriterion("full_time_millis <=", value, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisIn(List<Long> values) {
            addCriterion("full_time_millis in", values, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisNotIn(List<Long> values) {
            addCriterion("full_time_millis not in", values, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisBetween(Long value1, Long value2) {
            addCriterion("full_time_millis between", value1, value2, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andFullTimeMillisNotBetween(Long value1, Long value2) {
            addCriterion("full_time_millis not between", value1, value2, "fullTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisIsNull() {
            addCriterion("allotting_time_millis is null");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisIsNotNull() {
            addCriterion("allotting_time_millis is not null");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisEqualTo(Long value) {
            addCriterion("allotting_time_millis =", value, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisNotEqualTo(Long value) {
            addCriterion("allotting_time_millis <>", value, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisGreaterThan(Long value) {
            addCriterion("allotting_time_millis >", value, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisGreaterThanOrEqualTo(Long value) {
            addCriterion("allotting_time_millis >=", value, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisLessThan(Long value) {
            addCriterion("allotting_time_millis <", value, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisLessThanOrEqualTo(Long value) {
            addCriterion("allotting_time_millis <=", value, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisIn(List<Long> values) {
            addCriterion("allotting_time_millis in", values, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisNotIn(List<Long> values) {
            addCriterion("allotting_time_millis not in", values, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisBetween(Long value1, Long value2) {
            addCriterion("allotting_time_millis between", value1, value2, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottingTimeMillisNotBetween(Long value1, Long value2) {
            addCriterion("allotting_time_millis not between", value1, value2, "allottingTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisIsNull() {
            addCriterion("allotted_time_millis is null");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisIsNotNull() {
            addCriterion("allotted_time_millis is not null");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisEqualTo(Long value) {
            addCriterion("allotted_time_millis =", value, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisNotEqualTo(Long value) {
            addCriterion("allotted_time_millis <>", value, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisGreaterThan(Long value) {
            addCriterion("allotted_time_millis >", value, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisGreaterThanOrEqualTo(Long value) {
            addCriterion("allotted_time_millis >=", value, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisLessThan(Long value) {
            addCriterion("allotted_time_millis <", value, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisLessThanOrEqualTo(Long value) {
            addCriterion("allotted_time_millis <=", value, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisIn(List<Long> values) {
            addCriterion("allotted_time_millis in", values, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisNotIn(List<Long> values) {
            addCriterion("allotted_time_millis not in", values, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisBetween(Long value1, Long value2) {
            addCriterion("allotted_time_millis between", value1, value2, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andAllottedTimeMillisNotBetween(Long value1, Long value2) {
            addCriterion("allotted_time_millis not between", value1, value2, "allottedTimeMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisIsNull() {
            addCriterion("timeout_millis is null");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisIsNotNull() {
            addCriterion("timeout_millis is not null");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisEqualTo(Long value) {
            addCriterion("timeout_millis =", value, "timeoutMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisNotEqualTo(Long value) {
            addCriterion("timeout_millis <>", value, "timeoutMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisGreaterThan(Long value) {
            addCriterion("timeout_millis >", value, "timeoutMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisGreaterThanOrEqualTo(Long value) {
            addCriterion("timeout_millis >=", value, "timeoutMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisLessThan(Long value) {
            addCriterion("timeout_millis <", value, "timeoutMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisLessThanOrEqualTo(Long value) {
            addCriterion("timeout_millis <=", value, "timeoutMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisIn(List<Long> values) {
            addCriterion("timeout_millis in", values, "timeoutMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisNotIn(List<Long> values) {
            addCriterion("timeout_millis not in", values, "timeoutMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisBetween(Long value1, Long value2) {
            addCriterion("timeout_millis between", value1, value2, "timeoutMillis");
            return (Criteria) this;
        }

        public Criteria andTimeoutMillisNotBetween(Long value1, Long value2) {
            addCriterion("timeout_millis not between", value1, value2, "timeoutMillis");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 26 16:54:32 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _shadow_delivery_packet
     *
     * @mbg.generated Thu Dec 26 16:54:32 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}