package com.etcj.delivery.api.model;

import java.util.Date;

public class PlatMobileDevice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.id
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.device_id
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.mac
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private String mac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.assert_serial
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private String assertSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.version_code
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private String versionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.created_by
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.created_time
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.updated_by
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.updated_time
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.kitchen_id
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private String kitchenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_mobile_device.kitchen_name
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    private String kitchenName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.id
     *
     * @return the value of plat_mobile_device.id
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.id
     *
     * @param id the value for plat_mobile_device.id
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.device_id
     *
     * @return the value of plat_mobile_device.device_id
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.device_id
     *
     * @param deviceId the value for plat_mobile_device.device_id
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.mac
     *
     * @return the value of plat_mobile_device.mac
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.mac
     *
     * @param mac the value for plat_mobile_device.mac
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.assert_serial
     *
     * @return the value of plat_mobile_device.assert_serial
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public String getAssertSerial() {
        return assertSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.assert_serial
     *
     * @param assertSerial the value for plat_mobile_device.assert_serial
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setAssertSerial(String assertSerial) {
        this.assertSerial = assertSerial == null ? null : assertSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.version_code
     *
     * @return the value of plat_mobile_device.version_code
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public String getVersionCode() {
        return versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.version_code
     *
     * @param versionCode the value for plat_mobile_device.version_code
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode == null ? null : versionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.created_by
     *
     * @return the value of plat_mobile_device.created_by
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.created_by
     *
     * @param createdBy the value for plat_mobile_device.created_by
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.created_time
     *
     * @return the value of plat_mobile_device.created_time
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.created_time
     *
     * @param createdTime the value for plat_mobile_device.created_time
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.updated_by
     *
     * @return the value of plat_mobile_device.updated_by
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.updated_by
     *
     * @param updatedBy the value for plat_mobile_device.updated_by
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.updated_time
     *
     * @return the value of plat_mobile_device.updated_time
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.updated_time
     *
     * @param updatedTime the value for plat_mobile_device.updated_time
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.kitchen_id
     *
     * @return the value of plat_mobile_device.kitchen_id
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public String getKitchenId() {
        return kitchenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.kitchen_id
     *
     * @param kitchenId the value for plat_mobile_device.kitchen_id
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setKitchenId(String kitchenId) {
        this.kitchenId = kitchenId == null ? null : kitchenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_mobile_device.kitchen_name
     *
     * @return the value of plat_mobile_device.kitchen_name
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public String getKitchenName() {
        return kitchenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_mobile_device.kitchen_name
     *
     * @param kitchenName the value for plat_mobile_device.kitchen_name
     *
     * @mbg.generated Tue Dec 10 18:16:47 CST 2019
     */
    public void setKitchenName(String kitchenName) {
        this.kitchenName = kitchenName == null ? null : kitchenName.trim();
    }
}