package com.etcj.delivery.api.model;

import java.util.Date;

public class PlatAppVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.id
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.app_type
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String appType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.version
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.app_desc
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String appDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.is_force_update
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private Boolean forceUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.update_content
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String updateContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.update_version
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String updateVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.package_size
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private Integer packageSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.md5
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String md5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.app_status
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String appStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.platform
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.app_code
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.created_by
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.created_time
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.updated_by
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app_version.updated_time
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.id
     *
     * @return the value of plat_app_version.id
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.id
     *
     * @param id the value for plat_app_version.id
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.app_type
     *
     * @return the value of plat_app_version.app_type
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.app_type
     *
     * @param appType the value for plat_app_version.app_type
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.version
     *
     * @return the value of plat_app_version.version
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.version
     *
     * @param version the value for plat_app_version.version
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.app_desc
     *
     * @return the value of plat_app_version.app_desc
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getAppDesc() {
        return appDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.app_desc
     *
     * @param appDesc the value for plat_app_version.app_desc
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setAppDesc(String appDesc) {
        this.appDesc = appDesc == null ? null : appDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.is_force_update
     *
     * @return the value of plat_app_version.is_force_update
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public Boolean getForceUpdate() {
        return forceUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.is_force_update
     *
     * @param forceUpdate the value for plat_app_version.is_force_update
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setForceUpdate(Boolean forceUpdate) {
        this.forceUpdate = forceUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.update_content
     *
     * @return the value of plat_app_version.update_content
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getUpdateContent() {
        return updateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.update_content
     *
     * @param updateContent the value for plat_app_version.update_content
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setUpdateContent(String updateContent) {
        this.updateContent = updateContent == null ? null : updateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.update_version
     *
     * @return the value of plat_app_version.update_version
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getUpdateVersion() {
        return updateVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.update_version
     *
     * @param updateVersion the value for plat_app_version.update_version
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setUpdateVersion(String updateVersion) {
        this.updateVersion = updateVersion == null ? null : updateVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.package_size
     *
     * @return the value of plat_app_version.package_size
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public Integer getPackageSize() {
        return packageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.package_size
     *
     * @param packageSize the value for plat_app_version.package_size
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setPackageSize(Integer packageSize) {
        this.packageSize = packageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.md5
     *
     * @return the value of plat_app_version.md5
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.md5
     *
     * @param md5 the value for plat_app_version.md5
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.app_status
     *
     * @return the value of plat_app_version.app_status
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.app_status
     *
     * @param appStatus the value for plat_app_version.app_status
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus == null ? null : appStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.platform
     *
     * @return the value of plat_app_version.platform
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.platform
     *
     * @param platform the value for plat_app_version.platform
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.app_code
     *
     * @return the value of plat_app_version.app_code
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.app_code
     *
     * @param appCode the value for plat_app_version.app_code
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.created_by
     *
     * @return the value of plat_app_version.created_by
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.created_by
     *
     * @param createdBy the value for plat_app_version.created_by
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.created_time
     *
     * @return the value of plat_app_version.created_time
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.created_time
     *
     * @param createdTime the value for plat_app_version.created_time
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.updated_by
     *
     * @return the value of plat_app_version.updated_by
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.updated_by
     *
     * @param updatedBy the value for plat_app_version.updated_by
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app_version.updated_time
     *
     * @return the value of plat_app_version.updated_time
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app_version.updated_time
     *
     * @param updatedTime the value for plat_app_version.updated_time
     *
     * @mbg.generated Fri Dec 27 17:59:00 CST 2019
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}