package com.etcj.delivery.api.model;

import java.util.Date;

public class StationStation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.station1_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String station1Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.station2_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String station2Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.station1_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String station1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.station2_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String station2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.delivery_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Long deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.has_collected
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Byte hasCollected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.is_valid
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.is_available
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.create_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.create_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.update_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_station.update_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.id
     *
     * @return the value of station_station.id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.id
     *
     * @param id the value for station_station.id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.station1_id
     *
     * @return the value of station_station.station1_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getStation1Id() {
        return station1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.station1_id
     *
     * @param station1Id the value for station_station.station1_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setStation1Id(String station1Id) {
        this.station1Id = station1Id == null ? null : station1Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.station2_id
     *
     * @return the value of station_station.station2_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getStation2Id() {
        return station2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.station2_id
     *
     * @param station2Id the value for station_station.station2_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setStation2Id(String station2Id) {
        this.station2Id = station2Id == null ? null : station2Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.station1_name
     *
     * @return the value of station_station.station1_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getStation1Name() {
        return station1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.station1_name
     *
     * @param station1Name the value for station_station.station1_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setStation1Name(String station1Name) {
        this.station1Name = station1Name == null ? null : station1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.station2_name
     *
     * @return the value of station_station.station2_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getStation2Name() {
        return station2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.station2_name
     *
     * @param station2Name the value for station_station.station2_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setStation2Name(String station2Name) {
        this.station2Name = station2Name == null ? null : station2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.delivery_time
     *
     * @return the value of station_station.delivery_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Long getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.delivery_time
     *
     * @param deliveryTime the value for station_station.delivery_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setDeliveryTime(Long deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.has_collected
     *
     * @return the value of station_station.has_collected
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Byte getHasCollected() {
        return hasCollected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.has_collected
     *
     * @param hasCollected the value for station_station.has_collected
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setHasCollected(Byte hasCollected) {
        this.hasCollected = hasCollected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.is_valid
     *
     * @return the value of station_station.is_valid
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.is_valid
     *
     * @param valid the value for station_station.is_valid
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.is_available
     *
     * @return the value of station_station.is_available
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.is_available
     *
     * @param available the value for station_station.is_available
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.create_time
     *
     * @return the value of station_station.create_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.create_time
     *
     * @param createTime the value for station_station.create_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.create_user
     *
     * @return the value of station_station.create_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.create_user
     *
     * @param createUser the value for station_station.create_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.update_time
     *
     * @return the value of station_station.update_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.update_time
     *
     * @param updateTime the value for station_station.update_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_station.update_user
     *
     * @return the value of station_station.update_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_station.update_user
     *
     * @param updateUser the value for station_station.update_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}