package com.etcj.delivery.api.model;

import java.util.Date;

public class StationShop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.station_id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private String stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.shop_id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.shop_name
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.op_id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private String opId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.op_name
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private String opName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.is_take_order_station
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private Boolean takeOrderStation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.create_time
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.create_user
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.update_time
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.update_user
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_shop.is_valid
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.id
     *
     * @return the value of station_shop.id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.id
     *
     * @param id the value for station_shop.id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.station_id
     *
     * @return the value of station_shop.station_id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.station_id
     *
     * @param stationId the value for station_shop.station_id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.shop_id
     *
     * @return the value of station_shop.shop_id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.shop_id
     *
     * @param shopId the value for station_shop.shop_id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.shop_name
     *
     * @return the value of station_shop.shop_name
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.shop_name
     *
     * @param shopName the value for station_shop.shop_name
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.op_id
     *
     * @return the value of station_shop.op_id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public String getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.op_id
     *
     * @param opId the value for station_shop.op_id
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setOpId(String opId) {
        this.opId = opId == null ? null : opId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.op_name
     *
     * @return the value of station_shop.op_name
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public String getOpName() {
        return opName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.op_name
     *
     * @param opName the value for station_shop.op_name
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setOpName(String opName) {
        this.opName = opName == null ? null : opName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.is_take_order_station
     *
     * @return the value of station_shop.is_take_order_station
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public Boolean getTakeOrderStation() {
        return takeOrderStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.is_take_order_station
     *
     * @param takeOrderStation the value for station_shop.is_take_order_station
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setTakeOrderStation(Boolean takeOrderStation) {
        this.takeOrderStation = takeOrderStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.create_time
     *
     * @return the value of station_shop.create_time
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.create_time
     *
     * @param createTime the value for station_shop.create_time
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.create_user
     *
     * @return the value of station_shop.create_user
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.create_user
     *
     * @param createUser the value for station_shop.create_user
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.update_time
     *
     * @return the value of station_shop.update_time
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.update_time
     *
     * @param updateTime the value for station_shop.update_time
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.update_user
     *
     * @return the value of station_shop.update_user
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.update_user
     *
     * @param updateUser the value for station_shop.update_user
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_shop.is_valid
     *
     * @return the value of station_shop.is_valid
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_shop.is_valid
     *
     * @param valid the value for station_shop.is_valid
     *
     * @mbg.generated Sat Dec 07 11:02:14 CST 2019
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}