package com.etcj.delivery.api.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StationStationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public StationStationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStation1IdIsNull() {
            addCriterion("station1_id is null");
            return (Criteria) this;
        }

        public Criteria andStation1IdIsNotNull() {
            addCriterion("station1_id is not null");
            return (Criteria) this;
        }

        public Criteria andStation1IdEqualTo(String value) {
            addCriterion("station1_id =", value, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdNotEqualTo(String value) {
            addCriterion("station1_id <>", value, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdGreaterThan(String value) {
            addCriterion("station1_id >", value, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdGreaterThanOrEqualTo(String value) {
            addCriterion("station1_id >=", value, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdLessThan(String value) {
            addCriterion("station1_id <", value, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdLessThanOrEqualTo(String value) {
            addCriterion("station1_id <=", value, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdLike(String value) {
            addCriterion("station1_id like", value, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdNotLike(String value) {
            addCriterion("station1_id not like", value, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdIn(List<String> values) {
            addCriterion("station1_id in", values, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdNotIn(List<String> values) {
            addCriterion("station1_id not in", values, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdBetween(String value1, String value2) {
            addCriterion("station1_id between", value1, value2, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation1IdNotBetween(String value1, String value2) {
            addCriterion("station1_id not between", value1, value2, "station1Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdIsNull() {
            addCriterion("station2_id is null");
            return (Criteria) this;
        }

        public Criteria andStation2IdIsNotNull() {
            addCriterion("station2_id is not null");
            return (Criteria) this;
        }

        public Criteria andStation2IdEqualTo(String value) {
            addCriterion("station2_id =", value, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdNotEqualTo(String value) {
            addCriterion("station2_id <>", value, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdGreaterThan(String value) {
            addCriterion("station2_id >", value, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdGreaterThanOrEqualTo(String value) {
            addCriterion("station2_id >=", value, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdLessThan(String value) {
            addCriterion("station2_id <", value, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdLessThanOrEqualTo(String value) {
            addCriterion("station2_id <=", value, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdLike(String value) {
            addCriterion("station2_id like", value, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdNotLike(String value) {
            addCriterion("station2_id not like", value, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdIn(List<String> values) {
            addCriterion("station2_id in", values, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdNotIn(List<String> values) {
            addCriterion("station2_id not in", values, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdBetween(String value1, String value2) {
            addCriterion("station2_id between", value1, value2, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation2IdNotBetween(String value1, String value2) {
            addCriterion("station2_id not between", value1, value2, "station2Id");
            return (Criteria) this;
        }

        public Criteria andStation1NameIsNull() {
            addCriterion("station1_name is null");
            return (Criteria) this;
        }

        public Criteria andStation1NameIsNotNull() {
            addCriterion("station1_name is not null");
            return (Criteria) this;
        }

        public Criteria andStation1NameEqualTo(String value) {
            addCriterion("station1_name =", value, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameNotEqualTo(String value) {
            addCriterion("station1_name <>", value, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameGreaterThan(String value) {
            addCriterion("station1_name >", value, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameGreaterThanOrEqualTo(String value) {
            addCriterion("station1_name >=", value, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameLessThan(String value) {
            addCriterion("station1_name <", value, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameLessThanOrEqualTo(String value) {
            addCriterion("station1_name <=", value, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameLike(String value) {
            addCriterion("station1_name like", value, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameNotLike(String value) {
            addCriterion("station1_name not like", value, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameIn(List<String> values) {
            addCriterion("station1_name in", values, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameNotIn(List<String> values) {
            addCriterion("station1_name not in", values, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameBetween(String value1, String value2) {
            addCriterion("station1_name between", value1, value2, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation1NameNotBetween(String value1, String value2) {
            addCriterion("station1_name not between", value1, value2, "station1Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameIsNull() {
            addCriterion("station2_name is null");
            return (Criteria) this;
        }

        public Criteria andStation2NameIsNotNull() {
            addCriterion("station2_name is not null");
            return (Criteria) this;
        }

        public Criteria andStation2NameEqualTo(String value) {
            addCriterion("station2_name =", value, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameNotEqualTo(String value) {
            addCriterion("station2_name <>", value, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameGreaterThan(String value) {
            addCriterion("station2_name >", value, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameGreaterThanOrEqualTo(String value) {
            addCriterion("station2_name >=", value, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameLessThan(String value) {
            addCriterion("station2_name <", value, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameLessThanOrEqualTo(String value) {
            addCriterion("station2_name <=", value, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameLike(String value) {
            addCriterion("station2_name like", value, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameNotLike(String value) {
            addCriterion("station2_name not like", value, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameIn(List<String> values) {
            addCriterion("station2_name in", values, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameNotIn(List<String> values) {
            addCriterion("station2_name not in", values, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameBetween(String value1, String value2) {
            addCriterion("station2_name between", value1, value2, "station2Name");
            return (Criteria) this;
        }

        public Criteria andStation2NameNotBetween(String value1, String value2) {
            addCriterion("station2_name not between", value1, value2, "station2Name");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNull() {
            addCriterion("delivery_time is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNotNull() {
            addCriterion("delivery_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeEqualTo(Long value) {
            addCriterion("delivery_time =", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotEqualTo(Long value) {
            addCriterion("delivery_time <>", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThan(Long value) {
            addCriterion("delivery_time >", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("delivery_time >=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThan(Long value) {
            addCriterion("delivery_time <", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThanOrEqualTo(Long value) {
            addCriterion("delivery_time <=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIn(List<Long> values) {
            addCriterion("delivery_time in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotIn(List<Long> values) {
            addCriterion("delivery_time not in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeBetween(Long value1, Long value2) {
            addCriterion("delivery_time between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotBetween(Long value1, Long value2) {
            addCriterion("delivery_time not between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andHasCollectedIsNull() {
            addCriterion("has_collected is null");
            return (Criteria) this;
        }

        public Criteria andHasCollectedIsNotNull() {
            addCriterion("has_collected is not null");
            return (Criteria) this;
        }

        public Criteria andHasCollectedEqualTo(Byte value) {
            addCriterion("has_collected =", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedNotEqualTo(Byte value) {
            addCriterion("has_collected <>", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedGreaterThan(Byte value) {
            addCriterion("has_collected >", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedGreaterThanOrEqualTo(Byte value) {
            addCriterion("has_collected >=", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedLessThan(Byte value) {
            addCriterion("has_collected <", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedLessThanOrEqualTo(Byte value) {
            addCriterion("has_collected <=", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedIn(List<Byte> values) {
            addCriterion("has_collected in", values, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedNotIn(List<Byte> values) {
            addCriterion("has_collected not in", values, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedBetween(Byte value1, Byte value2) {
            addCriterion("has_collected between", value1, value2, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedNotBetween(Byte value1, Byte value2) {
            addCriterion("has_collected not between", value1, value2, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Boolean value) {
            addCriterion("is_valid =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Boolean value) {
            addCriterion("is_valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Boolean value) {
            addCriterion("is_valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Boolean value) {
            addCriterion("is_valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Boolean value) {
            addCriterion("is_valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Boolean> values) {
            addCriterion("is_valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Boolean> values) {
            addCriterion("is_valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Boolean value1, Boolean value2) {
            addCriterion("is_valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_valid not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andAvailableIsNull() {
            addCriterion("is_available is null");
            return (Criteria) this;
        }

        public Criteria andAvailableIsNotNull() {
            addCriterion("is_available is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableEqualTo(Boolean value) {
            addCriterion("is_available =", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableNotEqualTo(Boolean value) {
            addCriterion("is_available <>", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableGreaterThan(Boolean value) {
            addCriterion("is_available >", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_available >=", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableLessThan(Boolean value) {
            addCriterion("is_available <", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableLessThanOrEqualTo(Boolean value) {
            addCriterion("is_available <=", value, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableIn(List<Boolean> values) {
            addCriterion("is_available in", values, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableNotIn(List<Boolean> values) {
            addCriterion("is_available not in", values, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableBetween(Boolean value1, Boolean value2) {
            addCriterion("is_available between", value1, value2, "available");
            return (Criteria) this;
        }

        public Criteria andAvailableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_available not between", value1, value2, "available");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table station_station
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 07 14:09:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table station_station
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}