package com.etcj.delivery.api.model;

import java.util.Date;

public class StationWhite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.station_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.white_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String whiteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.has_collected
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Byte hasCollected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.delivery_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Long deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.is_valid
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Boolean valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.station_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.white_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String whiteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.create_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.create_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.update_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.update_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_white.is_available
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    private Byte available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.id
     *
     * @return the value of station_white.id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.id
     *
     * @param id the value for station_white.id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.station_id
     *
     * @return the value of station_white.station_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.station_id
     *
     * @param stationId the value for station_white.station_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setStationId(String stationId) {
        this.stationId = stationId == null ? null : stationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.white_id
     *
     * @return the value of station_white.white_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getWhiteId() {
        return whiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.white_id
     *
     * @param whiteId the value for station_white.white_id
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setWhiteId(String whiteId) {
        this.whiteId = whiteId == null ? null : whiteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.has_collected
     *
     * @return the value of station_white.has_collected
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Byte getHasCollected() {
        return hasCollected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.has_collected
     *
     * @param hasCollected the value for station_white.has_collected
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setHasCollected(Byte hasCollected) {
        this.hasCollected = hasCollected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.delivery_time
     *
     * @return the value of station_white.delivery_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Long getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.delivery_time
     *
     * @param deliveryTime the value for station_white.delivery_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setDeliveryTime(Long deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.is_valid
     *
     * @return the value of station_white.is_valid
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.is_valid
     *
     * @param valid the value for station_white.is_valid
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.station_name
     *
     * @return the value of station_white.station_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.station_name
     *
     * @param stationName the value for station_white.station_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.white_name
     *
     * @return the value of station_white.white_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getWhiteName() {
        return whiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.white_name
     *
     * @param whiteName the value for station_white.white_name
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setWhiteName(String whiteName) {
        this.whiteName = whiteName == null ? null : whiteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.create_time
     *
     * @return the value of station_white.create_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.create_time
     *
     * @param createTime the value for station_white.create_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.create_user
     *
     * @return the value of station_white.create_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.create_user
     *
     * @param createUser the value for station_white.create_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.update_time
     *
     * @return the value of station_white.update_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.update_time
     *
     * @param updateTime the value for station_white.update_time
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.update_user
     *
     * @return the value of station_white.update_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.update_user
     *
     * @param updateUser the value for station_white.update_user
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_white.is_available
     *
     * @return the value of station_white.is_available
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public Byte getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_white.is_available
     *
     * @param available the value for station_white.is_available
     *
     * @mbg.generated Sat Dec 07 14:09:21 CST 2019
     */
    public void setAvailable(Byte available) {
        this.available = available;
    }
}