package com.etcj.delivery.api.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WhiteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public WhiteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPoiIdIsNull() {
            addCriterion("poi_id is null");
            return (Criteria) this;
        }

        public Criteria andPoiIdIsNotNull() {
            addCriterion("poi_id is not null");
            return (Criteria) this;
        }

        public Criteria andPoiIdEqualTo(String value) {
            addCriterion("poi_id =", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdNotEqualTo(String value) {
            addCriterion("poi_id <>", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdGreaterThan(String value) {
            addCriterion("poi_id >", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdGreaterThanOrEqualTo(String value) {
            addCriterion("poi_id >=", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdLessThan(String value) {
            addCriterion("poi_id <", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdLessThanOrEqualTo(String value) {
            addCriterion("poi_id <=", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdLike(String value) {
            addCriterion("poi_id like", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdNotLike(String value) {
            addCriterion("poi_id not like", value, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdIn(List<String> values) {
            addCriterion("poi_id in", values, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdNotIn(List<String> values) {
            addCriterion("poi_id not in", values, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdBetween(String value1, String value2) {
            addCriterion("poi_id between", value1, value2, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiIdNotBetween(String value1, String value2) {
            addCriterion("poi_id not between", value1, value2, "poiId");
            return (Criteria) this;
        }

        public Criteria andPoiNameIsNull() {
            addCriterion("poi_name is null");
            return (Criteria) this;
        }

        public Criteria andPoiNameIsNotNull() {
            addCriterion("poi_name is not null");
            return (Criteria) this;
        }

        public Criteria andPoiNameEqualTo(String value) {
            addCriterion("poi_name =", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameNotEqualTo(String value) {
            addCriterion("poi_name <>", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameGreaterThan(String value) {
            addCriterion("poi_name >", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameGreaterThanOrEqualTo(String value) {
            addCriterion("poi_name >=", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameLessThan(String value) {
            addCriterion("poi_name <", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameLessThanOrEqualTo(String value) {
            addCriterion("poi_name <=", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameLike(String value) {
            addCriterion("poi_name like", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameNotLike(String value) {
            addCriterion("poi_name not like", value, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameIn(List<String> values) {
            addCriterion("poi_name in", values, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameNotIn(List<String> values) {
            addCriterion("poi_name not in", values, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameBetween(String value1, String value2) {
            addCriterion("poi_name between", value1, value2, "poiName");
            return (Criteria) this;
        }

        public Criteria andPoiNameNotBetween(String value1, String value2) {
            addCriterion("poi_name not between", value1, value2, "poiName");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterIsNull() {
            addCriterion("is_allow_enter is null");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterIsNotNull() {
            addCriterion("is_allow_enter is not null");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterEqualTo(Byte value) {
            addCriterion("is_allow_enter =", value, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterNotEqualTo(Byte value) {
            addCriterion("is_allow_enter <>", value, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterGreaterThan(Byte value) {
            addCriterion("is_allow_enter >", value, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_allow_enter >=", value, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterLessThan(Byte value) {
            addCriterion("is_allow_enter <", value, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterLessThanOrEqualTo(Byte value) {
            addCriterion("is_allow_enter <=", value, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterIn(List<Byte> values) {
            addCriterion("is_allow_enter in", values, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterNotIn(List<Byte> values) {
            addCriterion("is_allow_enter not in", values, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterBetween(Byte value1, Byte value2) {
            addCriterion("is_allow_enter between", value1, value2, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andIsAllowEnterNotBetween(Byte value1, Byte value2) {
            addCriterion("is_allow_enter not between", value1, value2, "isAllowEnter");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsIsNull() {
            addCriterion("number_of_floors is null");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsIsNotNull() {
            addCriterion("number_of_floors is not null");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsEqualTo(Integer value) {
            addCriterion("number_of_floors =", value, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsNotEqualTo(Integer value) {
            addCriterion("number_of_floors <>", value, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsGreaterThan(Integer value) {
            addCriterion("number_of_floors >", value, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_of_floors >=", value, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsLessThan(Integer value) {
            addCriterion("number_of_floors <", value, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsLessThanOrEqualTo(Integer value) {
            addCriterion("number_of_floors <=", value, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsIn(List<Integer> values) {
            addCriterion("number_of_floors in", values, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsNotIn(List<Integer> values) {
            addCriterion("number_of_floors not in", values, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsBetween(Integer value1, Integer value2) {
            addCriterion("number_of_floors between", value1, value2, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andNumberOfFloorsNotBetween(Integer value1, Integer value2) {
            addCriterion("number_of_floors not between", value1, value2, "numberOfFloors");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenIsNull() {
            addCriterion("is_odd_even is null");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenIsNotNull() {
            addCriterion("is_odd_even is not null");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenEqualTo(Byte value) {
            addCriterion("is_odd_even =", value, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenNotEqualTo(Byte value) {
            addCriterion("is_odd_even <>", value, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenGreaterThan(Byte value) {
            addCriterion("is_odd_even >", value, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_odd_even >=", value, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenLessThan(Byte value) {
            addCriterion("is_odd_even <", value, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenLessThanOrEqualTo(Byte value) {
            addCriterion("is_odd_even <=", value, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenIn(List<Byte> values) {
            addCriterion("is_odd_even in", values, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenNotIn(List<Byte> values) {
            addCriterion("is_odd_even not in", values, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenBetween(Byte value1, Byte value2) {
            addCriterion("is_odd_even between", value1, value2, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsOddEvenNotBetween(Byte value1, Byte value2) {
            addCriterion("is_odd_even not between", value1, value2, "isOddEven");
            return (Criteria) this;
        }

        public Criteria andIsHighLowIsNull() {
            addCriterion("is_high_low is null");
            return (Criteria) this;
        }

        public Criteria andIsHighLowIsNotNull() {
            addCriterion("is_high_low is not null");
            return (Criteria) this;
        }

        public Criteria andIsHighLowEqualTo(Byte value) {
            addCriterion("is_high_low =", value, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andIsHighLowNotEqualTo(Byte value) {
            addCriterion("is_high_low <>", value, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andIsHighLowGreaterThan(Byte value) {
            addCriterion("is_high_low >", value, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andIsHighLowGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_high_low >=", value, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andIsHighLowLessThan(Byte value) {
            addCriterion("is_high_low <", value, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andIsHighLowLessThanOrEqualTo(Byte value) {
            addCriterion("is_high_low <=", value, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andIsHighLowIn(List<Byte> values) {
            addCriterion("is_high_low in", values, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andIsHighLowNotIn(List<Byte> values) {
            addCriterion("is_high_low not in", values, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andIsHighLowBetween(Byte value1, Byte value2) {
            addCriterion("is_high_low between", value1, value2, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andIsHighLowNotBetween(Byte value1, Byte value2) {
            addCriterion("is_high_low not between", value1, value2, "isHighLow");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsIsNull() {
            addCriterion("number_of_elevators is null");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsIsNotNull() {
            addCriterion("number_of_elevators is not null");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsEqualTo(Integer value) {
            addCriterion("number_of_elevators =", value, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsNotEqualTo(Integer value) {
            addCriterion("number_of_elevators <>", value, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsGreaterThan(Integer value) {
            addCriterion("number_of_elevators >", value, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_of_elevators >=", value, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsLessThan(Integer value) {
            addCriterion("number_of_elevators <", value, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsLessThanOrEqualTo(Integer value) {
            addCriterion("number_of_elevators <=", value, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsIn(List<Integer> values) {
            addCriterion("number_of_elevators in", values, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsNotIn(List<Integer> values) {
            addCriterion("number_of_elevators not in", values, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsBetween(Integer value1, Integer value2) {
            addCriterion("number_of_elevators between", value1, value2, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andNumberOfElevatorsNotBetween(Integer value1, Integer value2) {
            addCriterion("number_of_elevators not between", value1, value2, "numberOfElevators");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNull() {
            addCriterion("delivery_time is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIsNotNull() {
            addCriterion("delivery_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeEqualTo(Long value) {
            addCriterion("delivery_time =", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotEqualTo(Long value) {
            addCriterion("delivery_time <>", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThan(Long value) {
            addCriterion("delivery_time >", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("delivery_time >=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThan(Long value) {
            addCriterion("delivery_time <", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeLessThanOrEqualTo(Long value) {
            addCriterion("delivery_time <=", value, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeIn(List<Long> values) {
            addCriterion("delivery_time in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotIn(List<Long> values) {
            addCriterion("delivery_time not in", values, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeBetween(Long value1, Long value2) {
            addCriterion("delivery_time between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryTimeNotBetween(Long value1, Long value2) {
            addCriterion("delivery_time not between", value1, value2, "deliveryTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andHasCollectedIsNull() {
            addCriterion("has_collected is null");
            return (Criteria) this;
        }

        public Criteria andHasCollectedIsNotNull() {
            addCriterion("has_collected is not null");
            return (Criteria) this;
        }

        public Criteria andHasCollectedEqualTo(Byte value) {
            addCriterion("has_collected =", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedNotEqualTo(Byte value) {
            addCriterion("has_collected <>", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedGreaterThan(Byte value) {
            addCriterion("has_collected >", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedGreaterThanOrEqualTo(Byte value) {
            addCriterion("has_collected >=", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedLessThan(Byte value) {
            addCriterion("has_collected <", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedLessThanOrEqualTo(Byte value) {
            addCriterion("has_collected <=", value, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedIn(List<Byte> values) {
            addCriterion("has_collected in", values, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedNotIn(List<Byte> values) {
            addCriterion("has_collected not in", values, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedBetween(Byte value1, Byte value2) {
            addCriterion("has_collected between", value1, value2, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andHasCollectedNotBetween(Byte value1, Byte value2) {
            addCriterion("has_collected not between", value1, value2, "hasCollected");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Byte value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Byte value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Byte value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Byte value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Byte value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Byte> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Byte> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Byte value1, Byte value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Byte value1, Byte value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table white
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 24 20:53:53 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table white
     *
     * @mbg.generated Tue Sep 24 20:53:53 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}