package com.tianmen.dao;

import com.tianmen.model.PlatAppVersion;
import com.tianmen.model.PlatAppVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatAppVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    long countByExample(PlatAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    int deleteByExample(PlatAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    int insert(PlatAppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    int insertSelective(PlatAppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    List<PlatAppVersion> selectByExample(PlatAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    PlatAppVersion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") PlatAppVersion record, @Param("example") PlatAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    int updateByExample(@Param("record") PlatAppVersion record, @Param("example") PlatAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    int updateByPrimaryKeySelective(PlatAppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_app_version
     *
     * @mbg.generated Thu Jan 09 15:27:08 CST 2020
     */
    int updateByPrimaryKey(PlatAppVersion record);

    int insertBatchSelective(List<PlatAppVersion> records);
}